# These are supported funding model platforms

github: [
  "streamich",
  "wardoost",
  "xobotyi",
  "Belco90",
  "ankithkonda",
  "ayush987goyal",
  "NullVoxPopuli",
  "lintuming",
  "Granipouss",
  "ythecombinator",
  "james2406",
  "jakapatb",
  "MrHuangJser",
  "zaguiini",
  "ppeeou",
  "liuyuchenzh",
  "brickspert",
  "artywhite",
  "PetterIve",
  "realdennis",
  "lvl99",
  "gelove",
  "KusStar",
  "xiaoxiangmoe",
  "nmccready",
  "mattleonowicz",
  "kevinnorris",
  "dubzzz",
  "dependabot[bot]",
  "ShizukuIchi",
  "ManojBahuguna",
  "Jivings",
  "Dosant",
  "zsh2401",
  "xiaoboost",
  "revskill10",
  "mtinner",
  "monkeywithacupcake",
  "mitchheddles",
  "maxzitron",
  "macinjoke",
  "jeetiss",
  "ilyalesik",
  "hijiangtao",
  "f",
  "elliottsj",
  "droganov",
  "denysdovhan",
  "dabuside",
  "benneq",
  "azukaar",
  "ariesjia",
  "andrico1234",
  "adesurirey",
  "OBe95",
  "FredyC",
  "Cretezy",
  "zyy7259",
  "zslabs",
  "vinitsood",
  "uxitten",
  "thevtm",
  "tanem",
  "suyingtao",
  "srph",
  "rkostrzewski",
  "qianL93",
  "o-alexandrov",
  "nucleartux",
  "natew",
  "maxmalov",
  "liaoyinglong",
  "koenvanzuijlen",
  "josmardias",
  "jeemyeong",
  "jazzqi",
  "jakyle",
  "jakeboone02",
  "inker",
  "glarivie",
  "garrettmaring",
  "dovidweisz",
  "daniel-hauser",
  "d-asensio",
  "charlax",
  "TylerR909",
  "Rogdham",
  "OctoD",
  "MajorBreakfast",
  "Jfelix61",
  "Flydiverny",
  "FlickerLogicalStack",
  "DmacMcgreg",
  "Dattaya",
  "Andrey-Bazhanov",
  "AlvaroBernalG"
]
